global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'edge-service'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'edge-service:9000' ]
  - job_name: 'book-service'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'book-service:8080' ]
  - job_name: 'suggestion-service'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'suggestion-service:8181' ]
