version: "3.8"
services:
  postgresql:
    image: "postgres:14.1"
    container_name: "postgresql"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=catalog
