apiVersion: v1
kind: ConfigMap
metadata:
  name: book-config
data:
  application.yml: |
    server:
      shutdown: graceful
    spring:
      lifecycle:
        timeout-per-shutdown-phase: 20s
      r2dbc:
        url: r2dbc:postgresql://polar-postgres:5432/catalog
