apiVersion: v1
kind: Service
metadata:
  name: suggestion-service
  labels:
    app: suggestion-service
spec:
  type: ClusterIP
  selector:
    app: suggestion-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8181
