version: "3.8"
services:

  # Applications

  book-service:
    depends_on:
      - fluent-bit
      - postgresql
      - tempo
    image: "book-service"
    container_name: "book-service"
    ports:
      - 8080:8080
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-1.12.1.jar
      - OTEL_SERVICE_NAME=book-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgresql:5432/catalog
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224

  suggestion-service:
    depends_on:
      - fluent-bit
    image: "suggestion-service"
    container_name: "suggestion-service"
    ports:
      - 8181:8181
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-1.12.1.jar
      - OTEL_SERVICE_NAME=suggestion-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
      - DEMO_BOOK_SERVICE_URI=http://book-service:8080
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
  
  edge-service:
    depends_on:
      - fluent-bit
    image: "edge-service"
    container_name: "edge-service"
    ports:
      - 9000:9000
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-1.12.1.jar
      - OTEL_SERVICE_NAME=edge-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
      - BOOK_SERVICE_URI=http://book-service:8080
      - SUGGESTION_SERVICE_URI=http://suggestion-service:8181
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
  
  # Backing Services

  postgresql:
    image: "postgres:14.1"
    container_name: "postgresql"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=catalog

  # Observability

  grafana:
    image: grafana/grafana:8.4.4
    container_name: grafana
    depends_on:
      - loki
      - prometheus
      - tempo
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./docker/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./docker/grafana/dashboards:/etc/grafana/provisioning/dashboards

  loki:
    image: grafana/loki:2.4.2
    container_name: loki
    depends_on:
      - fluent-bit
    ports:
      - "3100:3100"

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:2.4.2-amd64
    container_name: fluent-bit
    ports:
      - "24224:24224"
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./docker/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

  prometheus:
    image: prom/prometheus:v2.34.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  tempo:
    image: grafana/tempo:1.3.2
    container_name: tempo
    command: -config.file /etc/tempo-config.yml
    ports:
      - "3110:3100"     # Tempo
      - "4317:4317"     # OTel
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo-config.yml
